### ISSUE TITLE
Vulnerable to XSS

### ISSUE THREAD

**Issue by st-h** [KasperTidemann/ember-contenteditable-view#7]
I think the setContent function should html encode what it passes to the DOM, otherwise a entered script tag would get parsed as a script and introduce a vulnerability to XSS.

```
  setContent: function() {
    return this.$().html(Ember.Handlebars.Utils.escapeExpression(this.get('value')));
  }
```

I am not sure what the intention about the plaintext option is, so that probably still might need some tweaking.

**Comment by KasperTidemann** [comment]
That's true and has actually been adressed before. Thanks for bringing this up, I'll fix it (and component'ize the code) accordingly.
